// Traducciones para las respuestas de inversión

// INGLÉS
export const inversionAnswerUSD_EN = "This platform was created with the goal of changing the lives of our members, providing them with a real opportunity for work independence. Our purpose is to reach as many people as possible, transforming the way online work is done. And today, for a limited time only, we have a special offer for you, so you can join Flasti and start generating income right away.\n\nSUPER EXCLUSIVE LIMITED TIME OFFER!\n\nOriginal value: $50 USD | TODAY ONLY $10 USD\n\nPay once and access Flasti for life using PayPal or your local currency!\n\nTHE PRICE WILL RETURN TO ITS ORIGINAL VALUE OF $50 USD AT ANY TIME\n\nIf you think about it, this small investment is minimal compared to the income potential you can obtain starting today.\n\nRemember: This price has an 80% discount and is only available for a limited time. You're saving $40 USD one-time, right now! Only the most determined and committed will have the opportunity to take advantage of this offer. This is your moment! ✅ Don't let this opportunity slip away. Take advantage now before it's too late!\n\n⚠️ IMPORTANT: The price will return to its original value at any time. This exclusive offer is unique and registrations are about to run out.";

// PORTUGUÉS
export const inversionAnswerUSD_PT = "Esta plataforma foi criada com o objetivo de mudar a vida dos nossos membros, proporcionando-lhes uma oportunidade real de independência laboral. Nosso propósito é alcançar o maior número possível de pessoas, transformando a maneira como se trabalha online. E hoje, apenas por tempo limitado, temos uma oferta especial para você, para que possa se juntar à Flasti e começar a gerar renda desde já.\n\nSUPER OFERTA EXCLUSIVA POR TEMPO LIMITADO!\n\nValor original: $50 USD | APENAS HOJE $10 USD\n\nPague uma vez e acesse a Flasti para toda a vida usando PayPal ou sua moeda local!\n\nO PREÇO VOLTARÁ AO SEU VALOR ORIGINAL DE $50 USD A QUALQUER MOMENTO\n\nSe você pensar bem, este pequeno investimento é mínimo comparado com o potencial de renda que você pode obter a partir de hoje mesmo.\n\nLembre-se: Este preço tem 80% de desconto e é apenas por tempo limitado. Você está economizando $40 USD de uma só vez, agora mesmo! Apenas os mais decididos e comprometidos terão a oportunidade de aproveitar esta oferta. Este é o seu momento! ✅ Não deixe esta oportunidade escapar. Aproveite agora antes que seja tarde!\n\n⚠️ IMPORTANTE: O preço voltará ao seu valor original a qualquer momento. Esta oferta exclusiva é única e as inscrições estão prestes a se esgotar.";

// PORTUGUÉS (ARGENTINA)
export const inversionAnswerARS_PT = "Esta plataforma foi criada com o objetivo de mudar a vida dos nossos membros, proporcionando-lhes uma oportunidade real de independência laboral. Nosso propósito é alcançar o maior número possível de pessoas, transformando a maneira como se trabalha online. E hoje, apenas por tempo limitado, temos uma oferta especial para você, para que possa se juntar à Flasti e começar a gerar renda desde já.\n\nSUPER OFERTA EXCLUSIVA POR TEMPO LIMITADO!\n\nValor original: AR$ 57.500 | APENAS HOJE AR$ 11.500\n\nPague uma vez e acesse a Flasti para toda a vida usando Mercado Pago, cartão de débito e crédito, Pago Fácil ou Rapipago!\n\nO PREÇO VOLTARÁ AO SEU VALOR ORIGINAL DE AR$ 57.500 A QUALQUER MOMENTO\n\nSe você pensar bem, este pequeno investimento é mínimo comparado com o potencial de renda que você pode obter a partir de hoje mesmo.\n\nLembre-se: Este preço tem 80% de desconto e é apenas por tempo limitado. Você está economizando AR$ 46.000 de uma só vez, agora mesmo! Apenas os mais decididos e comprometidos terão a oportunidade de aproveitar esta oferta. Este é o seu momento! ✅ Não deixe esta oportunidade escapar. Aproveite agora antes que seja tarde!\n\n⚠️ IMPORTANTE: O preço voltará ao seu valor original a qualquer momento. Esta oferta exclusiva é única e as inscrições estão prestes a se esgotar.";

// INGLÉS (ARGENTINA)
export const inversionAnswerARS_EN = "This platform was created with the goal of changing the lives of our members, providing them with a real opportunity for work independence. Our purpose is to reach as many people as possible, transforming the way online work is done. And today, for a limited time only, we have a special offer for you, so you can join Flasti and start generating income right away.\n\nSUPER EXCLUSIVE LIMITED TIME OFFER!\n\nOriginal value: AR$ 57,500 | TODAY ONLY AR$ 11,500\n\nPay once and access Flasti for life using Mercado Pago, debit and credit card, Pago Fácil or Rapipago!\n\nTHE PRICE WILL RETURN TO ITS ORIGINAL VALUE OF AR$ 57,500 AT ANY TIME\n\nIf you think about it, this small investment is minimal compared to the income potential you can obtain starting today.\n\nRemember: This price has an 80% discount and is only available for a limited time. You're saving AR$ 46,000 one-time, right now! Only the most determined and committed will have the opportunity to take advantage of this offer. This is your moment! ✅ Don't let this opportunity slip away. Take advantage now before it's too late!\n\n⚠️ IMPORTANT: The price will return to its original value at any time. This exclusive offer is unique and registrations are about to run out.";
