// Traducciones para las respuestas de inversión

// INGLÉS
export const inversionAnswerUSD_EN = "We have designed different plans to adapt to various needs and budgets. Our most accessible option starts at a one-time payment of $3.90 USD (the equivalent in your local currency will be shown at checkout), an investment that many of our users recover in their first week of use.\n\n⚡ SUPER EXCLUSIVE LIMITED TIME OFFER!\n\nOnly $3.90 USD instead of $19.50 USD (80% OFF)\n\n💥 Pay once and access Flasti for life using PayPal or your local currency! 💥\n\n🚨 THE PRICE WILL RETURN TO ITS ORIGINAL VALUE OF $19.50 USD AT ANY TIME\n\nIf you think about it, this small investment is minimal compared to the income potential you can obtain starting today.\n\n💡 Remember: This price has an 80% discount and is only available for a limited time. You're saving $15.60 USD one-time, right now! Only the most determined and committed will have the opportunity to take advantage of this offer. This is your moment! ✅ Don't let this opportunity slip away. Take advantage now before it's too late!\n\n⚠️ IMPORTANT: The price will return to its original value at any time. This exclusive offer is unique and registrations are about to run out.";

// PORTUGUÉS
export const inversionAnswerUSD_PT = "Desenvolvemos diferentes planos para nos adaptarmos a várias necessidades e orçamentos. Nossa opção mais acessível começa com um pagamento único de $3.90 USD (o equivalente em sua moeda local será mostrado ao finalizar o pagamento), um investimento que muitos dos nossos usuários recuperam em sua primeira semana de uso.\n\n⚡ SUPER OFERTA EXCLUSIVA POR TEMPO LIMITADO!\n\nApenas $3.90 USD em vez de $19.50 USD (80% OFF)\n\n💥 Pague uma vez e acesse a Flasti para toda a vida usando PayPal ou sua moeda local! 💥\n\n🚨 O PREÇO VOLTARÁ AO SEU VALOR ORIGINAL DE $19.50 USD A QUALQUER MOMENTO\n\nSe você pensar bem, este pequeno investimento é mínimo comparado com o potencial de renda que você pode obter a partir de hoje mesmo.\n\n💡 Lembre-se: Este preço tem 80% de desconto e é apenas por tempo limitado. Você está economizando $15.60 USD de uma só vez, agora mesmo! Apenas os mais decididos e comprometidos terão a oportunidade de aproveitar esta oferta. Este é o seu momento! ✅ Não deixe esta oportunidade escapar. Aproveite agora antes que seja tarde!\n\n⚠️ IMPORTANTE: O preço voltará ao seu valor original a qualquer momento. Esta oferta exclusiva é única e as inscrições estão prestes a se esgotar.";

// PORTUGUÉS (ARGENTINA)
export const inversionAnswerARS_PT = "Desenvolvemos diferentes planos para nos adaptarmos a várias necessidades e orçamentos. Nossa opção mais acessível começa com um pagamento único de AR$ 1.000, um investimento que muitos dos nossos usuários recuperam em sua primeira semana de uso.\n\n⚡ SUPER OFERTA EXCLUSIVA POR TEMPO LIMITADO!\n\nApenas AR$ 1.000 em vez de AR$ 5.000 (80% OFF)\n\n💥 Pague uma vez e acesse a Flasti para toda a vida usando Mercado Pago ou PayPal! 💥\n\n🚨 O PREÇO VOLTARÁ AO SEU VALOR ORIGINAL DE AR$ 5.000 A QUALQUER MOMENTO\n\nSe você pensar bem, este pequeno investimento é mínimo comparado com o potencial de renda que você pode obter a partir de hoje mesmo.\n\n💡 Lembre-se: Este preço tem 80% de desconto e é apenas por tempo limitado. Você está economizando AR$ 4.000 de uma só vez, agora mesmo! Apenas os mais decididos e comprometidos terão a oportunidade de aproveitar esta oferta. Este é o seu momento! ✅ Não deixe esta oportunidade escapar. Aproveite agora antes que seja tarde!\n\n⚠️ IMPORTANTE: O preço voltará ao seu valor original a qualquer momento. Esta oferta exclusiva é única e as inscrições estão prestes a se esgotar.";

// INGLÉS (ARGENTINA)
export const inversionAnswerARS_EN = "We have designed different plans to adapt to various needs and budgets. Our most accessible option starts at a one-time payment of AR$ 1,000, an investment that many of our users recover in their first week of use.\n\n⚡ SUPER EXCLUSIVE LIMITED TIME OFFER!\n\nOnly AR$ 1,000 instead of AR$ 5,000 (80% OFF)\n\n💥 Pay once and access Flasti for life using Mercado Pago or PayPal! 💥\n\n🚨 THE PRICE WILL RETURN TO ITS ORIGINAL VALUE OF AR$ 5,000 AT ANY TIME\n\nIf you think about it, this small investment is minimal compared to the income potential you can obtain starting today.\n\n💡 Remember: This price has an 80% discount and is only available for a limited time. You're saving AR$ 4,000 one-time, right now! Only the most determined and committed will have the opportunity to take advantage of this offer. This is your moment! ✅ Don't let this opportunity slip away. Take advantage now before it's too late!\n\n⚠️ IMPORTANT: The price will return to its original value at any time. This exclusive offer is unique and registrations are about to run out.";
